name: Upload Shadow JAR to Existing Release

on:
  release:
    types: [published]

jobs:
  upload:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 22

      - name: Set up Gradle
        uses: gradle/gradle-build-action@v2
        with:
          gradle-version: 8.10

      - name: Make Gradle wrapper executable
        run: chmod +x ./gradlew

      - name: Build shadow jar (skip tests)
        run: ./gradlew shadowJar -x test

      - name: Upload shadow JAR to release
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: build/libs/synthdb-all.jar
          asset_name: synthdb-${{ github.event.release.tag_name }}.jar
          asset_content_type: application/java-archive
        env:
          GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}
