name: Build Shadow JAR

on:
  workflow_dispatch:  # allows manual runs

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 22

      - name: Set up Gradle
        uses: gradle/gradle-build-action@v2
        with:
          gradle-version: 8.10

      - name: Make Gradle wrapper executable
        run: chmod +x ./gradlew

      - name: Build shadow jar (skip tests)
        run: ./gradlew shadowJar -x test

      - name: Upload shadow jar as artifact
        uses: actions/upload-artifact@v4
        with:
          name: shadow-jar
          path: build/libs/*.jar
